import {
  hashChainSessions, getPermissionId, getOwnableValidator, getSpendingLimitsPolicy, getTimeFramePolicy,
  GLOBAL_CONSTANTS, SmartSessionMode, SMART_SESSIONS_ADDRESS,
} from '@rhinestone/module-sdk';
import { hashTypedData, toFunctionSelector } from 'viem';

// ── The EIP-712 type table for the Smart Sessions ENABLE digest (extracted from module-sdk 0.3.1) ──
const TYPES = {
  PolicyData: [{ name: 'policy', type: 'address' }, { name: 'initData', type: 'bytes' }],
  ActionData: [
    { name: 'actionTargetSelector', type: 'bytes4' },
    { name: 'actionTarget', type: 'address' },
    { name: 'actionPolicies', type: 'PolicyData[]' },
  ],
  ERC7739Context: [{ name: 'appDomainSeparator', type: 'bytes32' }, { name: 'contentName', type: 'string[]' }],
  ERC7739Data: [
    { name: 'allowedERC7739Content', type: 'ERC7739Context[]' },
    { name: 'erc1271Policies', type: 'PolicyData[]' },
  ],
  SignedPermissions: [
    { name: 'permitGenericPolicy', type: 'bool' },
    { name: 'permitAdminAccess', type: 'bool' },
    { name: 'ignoreSecurityAttestations', type: 'bool' },
    { name: 'permitERC4337Paymaster', type: 'bool' },
    { name: 'userOpPolicies', type: 'PolicyData[]' },
    { name: 'erc7739Policies', type: 'ERC7739Data' },
    { name: 'actions', type: 'ActionData[]' },
  ],
  SignedSession: [
    { name: 'account', type: 'address' },
    { name: 'permissions', type: 'SignedPermissions' },
    { name: 'sessionValidator', type: 'address' },
    { name: 'sessionValidatorInitData', type: 'bytes' },
    { name: 'salt', type: 'bytes32' },
    { name: 'smartSession', type: 'address' },
    { name: 'nonce', type: 'uint256' },
  ],
  ChainSession: [{ name: 'chainId', type: 'uint64' }, { name: 'session', type: 'SignedSession' }],
  MultiChainSession: [{ name: 'sessionsAndChainIds', type: 'ChainSession[]' }],
};
const DOMAIN = { name: 'SmartSession', version: '1' };  // NB: NO chainId, NO verifyingContract

// Independent recompute (only viem + the type table) — what Dev-2 will do on-device:
const rawHash = (chainSessions) =>
  hashTypedData({ domain: DOMAIN, types: TYPES, primaryType: 'MultiChainSession',
                  message: { sessionsAndChainIds: chainSessions } });

// Fixed, fully-literal inputs (well-known Hardhat acct0 = the SCA owner/account for the vector).
const ACCOUNT = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266';
const SESSION_VALIDATOR = '0x0000000000000000000000000000000000000777'; // session-key validator (fixed)
const SESSION_KEY_INITDATA = '0x000000000000000000000000cafecafecafecafecafecafecafecafecafecafe';
const SALT = '0x0000000000000000000000000000000000000000000000000000000000000001';
const NONCE = 0n;

// ⚠️ POLICY PLACEMENT (C3 on-chain finding — corrects the earlier vectors). The SpendingLimitsPolicy is
// IActionPolicy-only AND its checkAction parses an ERC-20 transfer/approve on the action TARGET (the token):
//   - it is REJECTED in `userOpPolicies` (UnsupportedPolicy 0x6a01dd01) — the original vectors put it there;
//   - on a non-token action (e.g. the DEX router multicall) it reverts at USE (PolicyViolation 0x3b577361).
// So the DCA spend cap = SpendingLimits as the ACTION policy on the spend-TOKEN's `approve` (caps what the
// router can pull); the TimeFrame WINDOW goes in `userOpPolicies` (IUserOpPolicy); the DEX swap is a SEPARATE
// time-boxed action. Proven on Base Sepolia: enable + USE-mode receipts (see copy-trading-c3-usemode-lock.md).
function buildSession(actions, userOpPolicies, permitERC4337Paymaster = false) {
  return {
    account: ACCOUNT,
    permissions: {
      permitGenericPolicy: false, permitAdminAccess: false,
      ignoreSecurityAttestations: false, permitERC4337Paymaster,
      userOpPolicies, erc7739Policies: { allowedERC7739Content: [], erc1271Policies: [] }, actions,
    },
    sessionValidator: SESSION_VALIDATOR,
    sessionValidatorInitData: SESSION_KEY_INITDATA,
    salt: SALT,
    smartSession: SMART_SESSIONS_ADDRESS,
    nonce: NONCE,
  };
}

// DCA scope inputs.
const USDC = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48';          // spend token (mainnet USDC, 6 decimals)
const CAP = 1_000_000n;                                              // 1 USDC cumulative cap (N3: total budget)
const DEX_ROUTER = '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45';    // Uniswap V3 router (example swap target)
const APPROVE_SELECTOR = '0x095ea7b3'; // approve(address,uint256) — the spend cap sits on the token approve
const SWAP_SELECTOR = '0x5ae401dc';    // multicall(uint256,bytes[]) — the DEX swap (separate, time-boxed)
const VALID_AFTER = 1748966016;        // window start (unix s)
const VALID_UNTIL = 1752958208;        // window end   (unix s)

// Real GLOBAL_CONSTANTS policy initData (generated by the audited helpers — not hand-typed).
const realSpend = getSpendingLimitsPolicy([{ token: USDC, limit: CAP }]);
const realTime = getTimeFramePolicy({ validAfter: VALID_AFTER, validUntil: VALID_UNTIL });

// Placeholder policy addresses (A/B/C isolate the typed-data encoding from the real addresses); the initData
// bytes are the REAL helper output so the encoding is representative.
const SPENDING_LIMIT_POLICY = '0x0000000000000000000000000000000000000511';
const TIMEFRAME_POLICY = '0x0000000000000000000000000000000000000522';

// The corrected DCA permission shape (used for B/C with placeholder addrs, D with real addrs).
const dcaShape = (spendAddr, timeAddr) => ({
  userOpPolicies: [{ policy: timeAddr, initData: realTime.initData }], // TimeFrame window (IUserOpPolicy)
  actions: [
    // cap: SpendingLimits on the spend-token approve (IActionPolicy) — caps what the router can pull
    { actionTargetSelector: APPROVE_SELECTOR, actionTarget: USDC, actionPolicies: [{ policy: spendAddr, initData: realSpend.initData }] },
    // swap: the DEX router call, time-boxed (separate action)
    { actionTargetSelector: SWAP_SELECTOR, actionTarget: DEX_ROUTER, actionPolicies: [{ policy: timeAddr, initData: realTime.initData }] },
  ],
});

// Vector A — minimal (no policies, no actions): isolates the typed-data encoding.
const sessionA = buildSession([], []);
// Vector B — corrected DCA shape, placeholder policy addrs, paymaster=false.
const shapeBC = dcaShape(SPENDING_LIMIT_POLICY, TIMEFRAME_POLICY);
const sessionB = buildSession(shapeBC.actions, shapeBC.userOpPolicies, false);
// Vector C — corrected DCA shape SPONSORED: identical to B but permitERC4337Paymaster=true (the real Pimlico enable).
const sessionC = buildSession(shapeBC.actions, shapeBC.userOpPolicies, true);

for (const [name, session] of [['A-minimal', sessionA], ['B-dca (paymaster=false)', sessionB], ['C-dca-sponsored (paymaster=true)', sessionC]]) {
  console.log(`\n──────── Vector ${name} ────────`);
  console.log('permissionId =', getPermissionId({ session }));
  for (const chainId of [1n, 8453n]) {
    const chainSessions = [{ chainId, session }];
    const sdk = hashChainSessions(chainSessions);
    const raw = rawHash(chainSessions);
    const match = sdk === raw ? 'MATCH ✓' : 'MISMATCH ✗';
    console.log(`  chainId=${chainId}: digestToSign = ${sdk}   (sdk vs raw-viem: ${match})`);
  }
}
console.log('\nmode(ENABLE) =', SmartSessionMode.ENABLE, '| smartSession(verifyingContract field) =', SMART_SESSIONS_ADDRESS);

// ── Vector D — REAL DCA pin: FULLY real (OwnableValidator + GLOBAL_CONSTANTS policies) + paymaster=true ──
// THE byte-exact target for Dev-1's app-built enable, with the C3-CORRECTED placement (cap on the USDC approve
// action, TimeFrame in userOpPolicies, swap as a separate action). NB: use the EMITTED OwnableValidator
// (getOwnableValidator().address / GLOBAL_CONSTANTS), NOT the top-level OWNABLE_VALIDATOR_ADDRESS export
// (0x2483DA.. = legacy) — same two-address gotcha as the policies.
const ov = getOwnableValidator({ threshold: 1, owners: [ACCOUNT] }); // owner = on-device EOA = account (7702 same-addr)
const shapeD = dcaShape(GLOBAL_CONSTANTS.SPENDING_LIMITS_POLICY_ADDRESS, GLOBAL_CONSTANTS.TIME_FRAME_POLICY_ADDRESS);
const sessionD = {
  account: ACCOUNT,
  permissions: {
    permitGenericPolicy: false, permitAdminAccess: false, ignoreSecurityAttestations: false,
    permitERC4337Paymaster: true,
    userOpPolicies: shapeD.userOpPolicies,
    erc7739Policies: { allowedERC7739Content: [], erc1271Policies: [] },
    actions: shapeD.actions,
  },
  sessionValidator: ov.address,
  sessionValidatorInitData: ov.initData,
  salt: SALT, smartSession: SMART_SESSIONS_ADDRESS, nonce: NONCE,
};
console.log('\n──────── Vector D — REAL DCA pin (OwnableValidator + real policies + paymaster=true, C3-corrected placement) ────────');
console.log('sessionValidator (EMITTED OwnableValidator) =', ov.address);
console.log('sessionValidatorInitData                    =', ov.initData);
console.log('cap policy   (SpendingLimits, on USDC.approve) =', GLOBAL_CONSTANTS.SPENDING_LIMITS_POLICY_ADDRESS, '| initData', realSpend.initData);
console.log('window policy(TimeFrame, userOpPolicies+swap)  =', GLOBAL_CONSTANTS.TIME_FRAME_POLICY_ADDRESS, '| initData', realTime.initData);
console.log('permissionId                                =', getPermissionId({ session: sessionD }));
for (const chainId of [1n, 8453n]) {
  const d = hashChainSessions([{ chainId, session: sessionD }]);
  const match = d === rawHash([{ chainId, session: sessionD }]) ? 'MATCH ✓' : 'MISMATCH ✗';
  console.log(`  chainId=${chainId}: digestToSign = ${d}   (sdk vs raw-viem: ${match})`);
}
console.log('\nnonce-getter (read-only via key-proxy): getNonce(bytes32 permissionId, address account) -> uint256');
console.log('  on SmartSession module', SMART_SESSIONS_ADDRESS, '| selector', toFunctionSelector('getNonce(bytes32,address)'));
